### PR TITLE
feat: merge features back into remote branch

### PR DESCRIPTION
**Pull request by SamTV12345**
This pr adds the following features:

- support for linking
- global store per user
- overwritable store location with env vars
- parallel fetching of configurations
- test coverage for the config retrieval
-  support for the run script section
- support for binaries running in local project like tsc

Sorry for the big pr. This branch also contains fixes for the mentioned compile errors @shahen94 on linux as I had your pipeline deactivated due to the fork.

### CODE REVIEW

**Comment by shahen94** [comment]
Thank you, @SamTV12345 , for Closing out the previous PR and taking a look at this one.
There are a lot of features in one PR! 😲 👏 

This will take a while to review & test. I'll keep this thread updated.

**Comment by SamTV12345** [comment]
> Thank you, @SamTV12345 , for Closing out the previous PR and taking a look at this one. There are a lot of features in one PR! 😲 👏
> 
> This will take a while to review & test. I'll keep this thread updated.

Sure :). If you have any questions feel free to ask. There is probably still a lot of improvement there especially on the resolving part. I tried to parallelize as much as possible to reduce latency between the pipes

**Comment by SamTV12345** [comment]
Hi @shahen94 did you have time for a review :) ?

**Comment by shahen94** [comment]
Amazing job, thanks @SamTV12345  and sorry for delayed reply.

Tested! merging

**Pull request merged**
